# Site Settings
title: "Jonathan Vasquez | Product Manager"
email: "jonathan@jvasquez.net"
description: "A showcase of my Product Management work, project execution, fintech innovation, and agile leadership."

baseurl: "" # Change if your site is hosted in a subdirectory
url: "https://jvasquezlabs.github.io"  # Your GitHub Pages site URL

# Theme & Plugins
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Navigation Menu (Sidebar)
navigation:
  main:
    - title: "Home"
      url: "/"
    - title: "Portfolio"
      url: "/portfolio/"

# Collections for Portfolio
collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

# Pagination Settings
paginate: 5
paginate_path: "/page:num/"

# Default Front Matter (Ensure Sidebar Appears)
defaults:
  - scope:
      path: ""
      type: pages
    values:
      header:
        overlay_image: /assets/images/header-bg.jpg
  - scope:
      path: ""
      type: posts
    values:
      header:
        overlay_image: /assets/images/header-bg.jpg
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: single
      sidebar: true


# Author Profile (Optional)
author:
  name: "Jonathan Vasquez"
  avatar: "/assets/images/profile.jpg"
  bio: "Product Manager specializing in Fintech and Proptech."
  location: "Miami, FL"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JVasquezLabs"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/jonathanvasquez"
