# Site settings
title: Jonathan Vasquez
email: jonathan@jvasquez.net
description: A showcase of my Product Management work, project execution, fintech innovation, and agile leadership.

baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://jvasquezlabs.github.io"  # Use your GitHub Pages site URL

twitter_username: none
github_username: JVasquezLabs
linkedin_username: JonathanVasquez

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"  # Fixed the missing quote
paginate: 5
timezone: "America/New_York"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-include-cache